import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@fontsource/roboto/700.css';
import StoreProvider from "./_component/StoreProvider";
import { UserProvider } from '@auth0/nextjs-auth0/client';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thai-camps.com | ",
  description: "Generated by create next app",
};


export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="./Themietlorfreeversion-Regular.ttf" />
      </head>
      <UserProvider>
        <body className={inter.className}>
          <StoreProvider>
            {children}
          </StoreProvider>
        </body>
      </UserProvider>

    </html>
  );
}
