import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@fontsource/roboto/700.css';
import HeaderPost from "./post/navbar/HeaderPost";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thai-camps.com",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <HeaderPost />
        {children}</body>
    </html>
  );
}
